package com.sms.vo;

import net.sf.json.JSONObject;

import java.util.Date;

public class CoursewareVO {
    private Integer id;
    private String name;
    private String description;
    private Integer courseId;
    private String photoUrl;
    private Byte isComboType;
    private String audioUrl;
    private String videoUrl;
//    private JSONObject comboData;
    private Byte isDisplayedOnSubjectPage;
    private Byte isDisplayedOnMainPage;
    private Integer managementStatusId;
    private Date createdTime;
    private String courseName;
    public CoursewareVO(){}
    public CoursewareVO(JSONObject jsonObject){
        if (jsonObject.has("id")) {
            this.setId(jsonObject.get("id").equals(null) ? null : jsonObject.getInt("id"));
        }
        if (jsonObject.has("name")) {
            this.setName(jsonObject.get("name").equals(null) ? null : jsonObject.getString("name"));
        }
        if (jsonObject.has("description")){
            this.setDescription(jsonObject.get("description").equals(null) ? null : jsonObject.getString("description"));
        }
        if (jsonObject.has("course_id")){
            this.setCourseId(jsonObject.get("course_id").equals(null) ? null : jsonObject.getInt("course_id"));
        }
        if (jsonObject.has("course_name")){
            this.setCourseName(jsonObject.get("course_name").equals(null) ? null : jsonObject.getString("course_name"));
        }
        if (jsonObject.has("photo_url")){
            this.setPhotoUrl(jsonObject.get("photo_url").equals(null) ? null : jsonObject.getString("photo_url"));
        }
        if (jsonObject.has("is_combo_type")){
            this.setIsComboType(jsonObject.get("is_combo_type").equals(null) ? null : (byte)jsonObject.getInt("is_combo_type"));
        }
        if (jsonObject.has("audio_url")){
            this.setAudioUrl(jsonObject.get("audio_url").equals(null)  ? null : jsonObject.getString("audio_url"));
        }
        if (jsonObject.has("video_url")){
            this.setVideoUrl(jsonObject.get("video_url").equals(null) ? null : jsonObject.getString("video_url"));
        }
        if (jsonObject.has("is_displayed_on_subject_page")){
            this.setIsDisplayedOnSubjectPage(jsonObject.get("is_displayed_on_subject_page").equals(null) ? null : (byte)jsonObject.getInt("is_displayed_on_subject_page"));
        }
        if (jsonObject.has("is_displayed_on_main_page")){
            this.setIsDisplayedOnMainPage(jsonObject.get("is_displayed_on_main_page").equals(null) ? null : (byte)jsonObject.getInt("is_displayed_on_main_page"));
        }
        if (jsonObject.has("management_status_id")){
            this.setManagementStatusId(jsonObject.get("is_displayed_on_main_page").equals(null) ? null : jsonObject.getInt("is_displayed_on_main_page"));
        }
        if (jsonObject.has("comboData")){
//            this.setComboData(jsonObject.get("combo_data").equals(null) ? null : jsonObject.get("combo_data"));
        }
    }

    public JSONObject serializeToJSONObject(){
        JSONObject jsonObject = new JSONObject();
        jsonObject.put("id",id);
        jsonObject.put("name",name);
        jsonObject.put("description",description);
        jsonObject.put("course_id",courseId);
        jsonObject.put("course_name",courseName);
        jsonObject.put("photo_url",photoUrl);
        jsonObject.put("is_combo_type",isComboType);
        jsonObject.put("audio_url",audioUrl);
        jsonObject.put("video_url",videoUrl);
//        jsonObject.put("combo_data",comboData);
        jsonObject.put("is_displayed_on_subject_page",isDisplayedOnSubjectPage);
        jsonObject.put("is_displayed_on_main_page",isDisplayedOnMainPage);
        jsonObject.put("management_stataus_id",managementStatusId);
        return jsonObject;
    }
    public String getCourseName() {
        return courseName;
    }

    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.id
     *
     * @return the value of courseware.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.id
     *
     * @param id the value for courseware.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.name
     *
     * @return the value of courseware.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.name
     *
     * @param name the value for courseware.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.description
     *
     * @return the value of courseware.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.description
     *
     * @param description the value for courseware.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.course_id
     *
     * @return the value of courseware.course_id
     *
     * @mbggenerated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.course_id
     *
     * @param courseId the value for courseware.course_id
     *
     * @mbggenerated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.photo_url
     *
     * @return the value of courseware.photo_url
     *
     * @mbggenerated
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.photo_url
     *
     * @param photoUrl the value for courseware.photo_url
     *
     * @mbggenerated
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl == null ? null : photoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.is_combo_type
     *
     * @return the value of courseware.is_combo_type
     *
     * @mbggenerated
     */
    public Byte getIsComboType() {
        return isComboType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.is_combo_type
     *
     * @param isComboType the value for courseware.is_combo_type
     *
     * @mbggenerated
     */
    public void setIsComboType(Byte isComboType) {
        this.isComboType = isComboType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.audio_url
     *
     * @return the value of courseware.audio_url
     *
     * @mbggenerated
     */
    public String getAudioUrl() {
        return audioUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.audio_url
     *
     * @param audioUrl the value for courseware.audio_url
     *
     * @mbggenerated
     */
    public void setAudioUrl(String audioUrl) {
        this.audioUrl = audioUrl == null ? null : audioUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.video_url
     *
     * @return the value of courseware.video_url
     *
     * @mbggenerated
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.video_url
     *
     * @param videoUrl the value for courseware.video_url
     *
     * @mbggenerated
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl == null ? null : videoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.is_displayed_on_subject_page
     *
     * @return the value of courseware.is_displayed_on_subject_page
     *
     * @mbggenerated
     */
    public Byte getIsDisplayedOnSubjectPage() {
        return isDisplayedOnSubjectPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.is_displayed_on_subject_page
     *
     * @param isDisplayedOnSubjectPage the value for courseware.is_displayed_on_subject_page
     *
     * @mbggenerated
     */
    public void setIsDisplayedOnSubjectPage(Byte isDisplayedOnSubjectPage) {
        this.isDisplayedOnSubjectPage = isDisplayedOnSubjectPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.is_displayed_on_main_page
     *
     * @return the value of courseware.is_displayed_on_main_page
     *
     * @mbggenerated
     */
    public Byte getIsDisplayedOnMainPage() {
        return isDisplayedOnMainPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.is_displayed_on_main_page
     *
     * @param isDisplayedOnMainPage the value for courseware.is_displayed_on_main_page
     *
     * @mbggenerated
     */
    public void setIsDisplayedOnMainPage(Byte isDisplayedOnMainPage) {
        this.isDisplayedOnMainPage = isDisplayedOnMainPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.management_status_id
     *
     * @return the value of courseware.management_status_id
     *
     * @mbggenerated
     */
    public Integer getManagementStatusId() {
        return managementStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.management_status_id
     *
     * @param managementStatusId the value for courseware.management_status_id
     *
     * @mbggenerated
     */
    public void setManagementStatusId(Integer managementStatusId) {
        this.managementStatusId = managementStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.created_time
     *
     * @return the value of courseware.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.created_time
     *
     * @param createdTime the value for courseware.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
}