package com.sms.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.sms.model.Courseware;

import java.util.List;

@Repository
public interface CoursewareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware
     *
     * @mbggenerated
     */
    int insert(Courseware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware
     *
     * @mbggenerated
     */
    int insertSelective(Courseware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware
     *
     * @mbggenerated
     */
    Courseware selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Courseware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Courseware record);

    int getCountByCourseId(@Param("courseId") Integer courseId);

    List<Courseware> selectByCourseIdAndStartIdAndLimitAndAsc(@Param("courseId")Integer courseId, @Param("pageStartId")int pageStartId, @Param("countPerPage")int countPerPage);

    List<Courseware> selectByCourseIdAndEndIdAndLimitAndDesc(@Param("courseId")Integer courseId, @Param("pageEndId")int pageEndId, @Param("countPerPage")int countPerPage);
}