package com.sms.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.sms.model.Course;

import java.util.List;

@Repository
public interface CourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    int insert(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    int insertSelective(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    Course selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Course record);

    int getCountBySubjectId(@Param("subjectId") Integer subjectId);

    List<Course> selectBySubjectIdAndStartIdAndLimitAndAsc(@Param("subjectId")Integer subjectId, @Param("pageStartId")int pageStartId, @Param("countPerPage")int countPerPage);

    List<Course> selectBySubjectIdAndEndIdAndLimitAndDesc(@Param("subjectId")Integer subjectId, @Param("pageEndId")int pageEndId, @Param("countPerPage")int countPerPage);
}