package com.sms.dao;

import org.springframework.stereotype.Repository;

import com.sms.model.FeeType;

import java.util.List;

@Repository
public interface FeeTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fee_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fee_type
     *
     * @mbggenerated
     */
    int insert(FeeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fee_type
     *
     * @mbggenerated
     */
    int insertSelective(FeeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fee_type
     *
     * @mbggenerated
     */
    FeeType selectByPrimaryKey(Integer id);

    List<FeeType> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fee_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FeeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fee_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FeeType record);
}