package com.sms.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.sms.model.GenericItem;
import com.sms.model.Group;

@Repository
public interface GroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated
     */
    int insert(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated
     */
    int insertSelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated
     */
    Group selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Group record);
    
    Group selectByName(String name);
    
    List<Group> selectByBranchSchoolIdAndPageAndAsc(@Param("branchSchoolId")Integer branchSchoolId, @Param("pageStartId")int pageStartId, @Param("countPerPage")int countPerPage);
    
    List<Group> selectByBranchSchoolIdAndPageAndDesc(@Param("branchSchoolId")Integer branchSchoolId, @Param("pageEndId")int pageEndId, @Param("countPerPage")int countPerPage);
    
    int getCountByBranchSchoolId(@Param("branchSchoolId")Integer branchSchoolId);
    
    List<Group> selectByIds(@Param("ids")List<Integer> ids);
    
    List<GenericItem> selectGroupLeaderNamesByGroupIds(@Param("groupIds")List<Integer> groupIds);
    
    List<GenericItem> selectGroupLeaderTelephoneNumbersByGroupIds(@Param("groupIds")List<Integer> groupIds);
    
    List<GenericItem> selectMemberCountByGroupIds(@Param("groupIds")List<Integer> groupIds);
    
    List<Group> selectByBranchSchoolId(@Param("branchSchoolId")Integer branchSchoolId);
}