package com.sms.dao;

import org.springframework.stereotype.Repository;

import com.sms.model.InformationSubtypeDictionary;

@Repository
public interface InformationSubtypeDictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_subtype_dictionary
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_subtype_dictionary
     *
     * @mbggenerated
     */
    int insert(InformationSubtypeDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_subtype_dictionary
     *
     * @mbggenerated
     */
    int insertSelective(InformationSubtypeDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_subtype_dictionary
     *
     * @mbggenerated
     */
    InformationSubtypeDictionary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_subtype_dictionary
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(InformationSubtypeDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_subtype_dictionary
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InformationSubtypeDictionary record);
}