package com.sms.dao;

import org.springframework.stereotype.Repository;

import com.sms.model.InformationTypeDictionary;

@Repository
public interface InformationTypeDictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_type_dictionary
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_type_dictionary
     *
     * @mbggenerated
     */
    int insert(InformationTypeDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_type_dictionary
     *
     * @mbggenerated
     */
    int insertSelective(InformationTypeDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_type_dictionary
     *
     * @mbggenerated
     */
    InformationTypeDictionary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_type_dictionary
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(InformationTypeDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_type_dictionary
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InformationTypeDictionary record);
}