package com.sms.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.sms.model.Information;

import java.util.List;

@Repository
public interface InformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information
     *
     * @mbggenerated
     */
    int insert(Information record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information
     *
     * @mbggenerated
     */
    int insertSelective(Information record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information
     *
     * @mbggenerated
     */
    Information selectByPrimaryKey(Integer id);

    List<Information> selectByTypeAndStartIdAndLimitAndAsc(@Param("informationTypeId") Integer informationTypeId, @Param("informationSubtypeId") Integer informationSubtypeId, @Param("pageStartId")Integer pageStartId, @Param("countPerPage")Integer countPerPage);

    List<Information> selectByTypeAndStartIdAndLimitAndDesc(@Param("informationTypeId") Integer informationTypeId, @Param("informationSubtypeId") Integer informationSubtypeId, @Param("pageStartId")Integer pageStartId, @Param("countPerPage")Integer countPerPage);

    Integer getCountByType(@Param("informationTypeId") Integer informationTypeId, @Param("informationSubtypeId") Integer informationSubtypeId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Information record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Information record);
}