package com.sms.dao;

import org.springframework.stereotype.Repository;

import com.sms.model.ManagementStatusDictionary;

@Repository
public interface ManagementStatusDictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table management_status_dictionary
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table management_status_dictionary
     *
     * @mbggenerated
     */
    int insert(ManagementStatusDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table management_status_dictionary
     *
     * @mbggenerated
     */
    int insertSelective(ManagementStatusDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table management_status_dictionary
     *
     * @mbggenerated
     */
    ManagementStatusDictionary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table management_status_dictionary
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ManagementStatusDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table management_status_dictionary
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ManagementStatusDictionary record);
}