package com.sms.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.sms.model.Member;

@Repository
public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated
     */
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated
     */
    int insertSelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated
     */
    Member selectByPrimaryKey(Integer id);

    Member selectByMemberName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Member record);
    
    int getCountByGroupId(@Param("groupId")Integer groupId);
    
    List<Member> selectByGroupIdAndStartIdAndLimitAndAsc(@Param("groupId")Integer groupId, @Param("pageStartId")int pageStartId, @Param("countPerPage")int countPerPage);
    
    List<Member> selectByGroupIdAndEndIdAndLimitAndDesc(@Param("groupId")Integer groupId, @Param("pageEndId")int pageEndId, @Param("countPerPage")int countPerPage);
}