package com.sms.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.sms.model.Monitor;

@Repository
public interface MonitorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor
     *
     * @mbggenerated
     */
    int insert(Monitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor
     *
     * @mbggenerated
     */
    int insertSelective(Monitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor
     *
     * @mbggenerated
     */
    Monitor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Monitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Monitor record);
    
    List<Monitor> selectByGroupId(Integer groupId);
    
    Monitor selectByName(String name);
}