package com.sms.dao;

import org.springframework.stereotype.Repository;

import com.sms.model.RoleDictionary;

@Repository
public interface RoleDictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_dictionary
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_dictionary
     *
     * @mbggenerated
     */
    int insert(RoleDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_dictionary
     *
     * @mbggenerated
     */
    int insertSelective(RoleDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_dictionary
     *
     * @mbggenerated
     */
    RoleDictionary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_dictionary
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoleDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_dictionary
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleDictionary record);
}