package com.sms.dao;

import com.sms.model.SchoolInformation;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SchoolInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_information
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_information
     *
     * @mbggenerated
     */
    int insert(SchoolInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_information
     *
     * @mbggenerated
     */
    int insertSelective(SchoolInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_information
     *
     * @mbggenerated
     */
    SchoolInformation selectByPrimaryKey(Integer id);

    List<SchoolInformation> selectByTypeAndStartIdAndLimitAndAsc(@Param("informationTypeId") Integer informationTypeId, @Param("informationSubtypeId") Integer informationSubtypeId, @Param("pageStartId")Integer pageStartId, @Param("countPerPage")Integer countPerPage);

    List<SchoolInformation> selectByTypeAndStartIdAndLimitAndDesc(@Param("informationTypeId") Integer informationTypeId, @Param("informationSubtypeId") Integer informationSubtypeId, @Param("pageStartId")Integer pageStartId, @Param("countPerPage")Integer countPerPage);

    Integer getCountByType(@Param("informationTypeId") Integer informationTypeId, @Param("informationSubtypeId") Integer informationSubtypeId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SchoolInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SchoolInformation record);
}