package com.sms.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.sms.model.BranchSchoolCount;
import com.sms.model.School;
import com.sms.model.SchoolPresident;

@Repository
public interface SchoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated
     */
    int insert(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated
     */
    int insertSelective(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated
     */
    School selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(School record);
    
    public List<School> selectByPageStartIdAndLimitAndAsc(@Param("pageStartId")int pageStartId, @Param("countPerPage")int countPerPage);
    
    public List<School> selectByPageEndIdAndLimitAndDesc(@Param("pageEndId")int pageEndId, @Param("countPerPage")int countPerPage);
    
    public List<School> selectBySchoolIds(@Param("schoolIds")List<Integer> schoolIds);
    
    /* TBD */
    
    public School selectByName(String name);
    
    public int getTotalSchoolCount();
    
    public List<BranchSchoolCount> selectBranchSchoolCountBySchoolIds(@Param("schoolIds")List<Integer> schoolIds);
    
    public List<SchoolPresident> selectSchoolPresidentBySchoolIds(@Param("schoolIds")List<Integer> schoolIds);
    
    public List<School> selectAll();
}