package com.sms.dao;

import org.springframework.stereotype.Repository;

import com.sms.model.SchoolTypeDictionary;

@Repository
public interface SchoolTypeDictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_type_dictionary
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_type_dictionary
     *
     * @mbggenerated
     */
    int insert(SchoolTypeDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_type_dictionary
     *
     * @mbggenerated
     */
    int insertSelective(SchoolTypeDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_type_dictionary
     *
     * @mbggenerated
     */
    SchoolTypeDictionary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_type_dictionary
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SchoolTypeDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_type_dictionary
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SchoolTypeDictionary record);
}