package com.sms.dao;

import org.springframework.stereotype.Repository;

import com.sms.model.StudentReport;

@Repository
public interface StudentReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_report
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_report
     *
     * @mbggenerated
     */
    int insert(StudentReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_report
     *
     * @mbggenerated
     */
    int insertSelective(StudentReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_report
     *
     * @mbggenerated
     */
    StudentReport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_report
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StudentReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_report
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StudentReport record);
}