package com.sms.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.jmx.export.annotation.ManagedOperationParameter;
import org.springframework.stereotype.Repository;

import com.sms.model.Subject;

import java.util.List;

@Repository
public interface SubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated
     */
    int insert(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated
     */
    int insertSelective(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated
     */
    Subject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Subject record);

    int getCountBySchoolId(@Param("schoolId") Integer schoolId);

    List<Subject> selectBySchoolIdAndStartIdAndLimitAndAsc(@Param("schoolId")Integer schoolId, @Param("pageStartId")int pageStartId, @Param("countPerPage")int countPerPage);

    List<Subject> selectBySchoolIdAndEndIdAndLimitAndDesc(@Param("schoolId")Integer schoolId, @Param("pageEndId")int pageEndId, @Param("countPerPage")int countPerPage);
}