package com.sms.model;

import java.util.Date;

public class Courseware {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.course_id
     *
     * @mbggenerated
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.photo_url
     *
     * @mbggenerated
     */
    private String photoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.is_combo_type
     *
     * @mbggenerated
     */
    private Byte isComboType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.audio_url
     *
     * @mbggenerated
     */
    private String audioUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.video_url
     *
     * @mbggenerated
     */
    private String videoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.combo_data
     *
     * @mbggenerated
     */
    private Object comboData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.is_displayed_on_subject_page
     *
     * @mbggenerated
     */
    private Byte isDisplayedOnSubjectPage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.is_displayed_on_main_page
     *
     * @mbggenerated
     */
    private Byte isDisplayedOnMainPage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.management_status_id
     *
     * @mbggenerated
     */
    private Integer managementStatusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.id
     *
     * @return the value of courseware.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.id
     *
     * @param id the value for courseware.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.name
     *
     * @return the value of courseware.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.name
     *
     * @param name the value for courseware.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.description
     *
     * @return the value of courseware.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.description
     *
     * @param description the value for courseware.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.course_id
     *
     * @return the value of courseware.course_id
     *
     * @mbggenerated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.course_id
     *
     * @param courseId the value for courseware.course_id
     *
     * @mbggenerated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.photo_url
     *
     * @return the value of courseware.photo_url
     *
     * @mbggenerated
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.photo_url
     *
     * @param photoUrl the value for courseware.photo_url
     *
     * @mbggenerated
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl == null ? null : photoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.is_combo_type
     *
     * @return the value of courseware.is_combo_type
     *
     * @mbggenerated
     */
    public Byte getIsComboType() {
        return isComboType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.is_combo_type
     *
     * @param isComboType the value for courseware.is_combo_type
     *
     * @mbggenerated
     */
    public void setIsComboType(Byte isComboType) {
        this.isComboType = isComboType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.audio_url
     *
     * @return the value of courseware.audio_url
     *
     * @mbggenerated
     */
    public String getAudioUrl() {
        return audioUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.audio_url
     *
     * @param audioUrl the value for courseware.audio_url
     *
     * @mbggenerated
     */
    public void setAudioUrl(String audioUrl) {
        this.audioUrl = audioUrl == null ? null : audioUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.video_url
     *
     * @return the value of courseware.video_url
     *
     * @mbggenerated
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.video_url
     *
     * @param videoUrl the value for courseware.video_url
     *
     * @mbggenerated
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl == null ? null : videoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.combo_data
     *
     * @return the value of courseware.combo_data
     *
     * @mbggenerated
     */
    public Object getComboData() {
        return comboData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.combo_data
     *
     * @param comboData the value for courseware.combo_data
     *
     * @mbggenerated
     */
    public void setComboData(Object comboData) {
        this.comboData = comboData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.is_displayed_on_subject_page
     *
     * @return the value of courseware.is_displayed_on_subject_page
     *
     * @mbggenerated
     */
    public Byte getIsDisplayedOnSubjectPage() {
        return isDisplayedOnSubjectPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.is_displayed_on_subject_page
     *
     * @param isDisplayedOnSubjectPage the value for courseware.is_displayed_on_subject_page
     *
     * @mbggenerated
     */
    public void setIsDisplayedOnSubjectPage(Byte isDisplayedOnSubjectPage) {
        this.isDisplayedOnSubjectPage = isDisplayedOnSubjectPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.is_displayed_on_main_page
     *
     * @return the value of courseware.is_displayed_on_main_page
     *
     * @mbggenerated
     */
    public Byte getIsDisplayedOnMainPage() {
        return isDisplayedOnMainPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.is_displayed_on_main_page
     *
     * @param isDisplayedOnMainPage the value for courseware.is_displayed_on_main_page
     *
     * @mbggenerated
     */
    public void setIsDisplayedOnMainPage(Byte isDisplayedOnMainPage) {
        this.isDisplayedOnMainPage = isDisplayedOnMainPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.management_status_id
     *
     * @return the value of courseware.management_status_id
     *
     * @mbggenerated
     */
    public Integer getManagementStatusId() {
        return managementStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.management_status_id
     *
     * @param managementStatusId the value for courseware.management_status_id
     *
     * @mbggenerated
     */
    public void setManagementStatusId(Integer managementStatusId) {
        this.managementStatusId = managementStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.created_time
     *
     * @return the value of courseware.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.created_time
     *
     * @param createdTime the value for courseware.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
}