package com.sms.model;

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.math.BigDecimal;

public class Fee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee.fee_type_id
     *
     * @mbggenerated
     */
    private Integer feeTypeId;

    private String feeTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee.course_id
     *
     * @mbggenerated
     */
//    @JsonIgnore
//    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee.school_id
     *
     * @mbggenerated
     */
//    @JsonIgnore
//    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee.branch_school_id
     *
     * @mbggenerated
     */
//    @JsonIgnore
//    private Integer branchSchoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee.group_id
     *
     * @mbggenerated
     */
//    @JsonIgnore
//    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee.member_id
     *
     * @mbggenerated
     */
//    @JsonIgnore
//    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee.management_status_id
     *
     * @mbggenerated
     */
    private Integer managementStatusId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee.id
     *
     * @return the value of fee.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee.id
     *
     * @param id the value for fee.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee.name
     *
     * @return the value of fee.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee.name
     *
     * @param name the value for fee.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee.fee_type_id
     *
     * @return the value of fee.fee_type_id
     *
     * @mbggenerated
     */
    public Integer getFeeTypeId() {
        return feeTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee.fee_type_id
     *
     * @param feeTypeId the value for fee.fee_type_id
     *
     * @mbggenerated
     */
    public void setFeeTypeId(Integer feeTypeId) {
        this.feeTypeId = feeTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee.course_id
     *
     * @return the value of fee.course_id
     *
     * @mbggenerated
     */
//    public Integer getCourseId() {
//        return courseId;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee.course_id
     *
     * @param courseId the value for fee.course_id
     *
     * @mbggenerated
     */
//    public void setCourseId(Integer courseId) {
//        this.courseId = courseId;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee.school_id
     *
     * @return the value of fee.school_id
     *
     * @mbggenerated
     */
//    public Integer getSchoolId() {
//        return schoolId;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee.school_id
     *
     * @param schoolId the value for fee.school_id
     *
     * @mbggenerated
     */
//    public void setSchoolId(Integer schoolId) {
//        this.schoolId = schoolId;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee.branch_school_id
     *
     * @return the value of fee.branch_school_id
     *
     * @mbggenerated
     */
//    public Integer getBranchSchoolId() {
//        return branchSchoolId;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee.branch_school_id
     *
     * @param branchSchoolId the value for fee.branch_school_id
     *
     * @mbggenerated
     */
//    public void setBranchSchoolId(Integer branchSchoolId) {
//        this.branchSchoolId = branchSchoolId;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee.group_id
     *
     * @return the value of fee.group_id
     *
     * @mbggenerated
     */
//    public Integer getGroupId() {
//        return groupId;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee.group_id
     *
     * @param groupId the value for fee.group_id
     *
     * @mbggenerated
     */
//    public void setGroupId(Integer groupId) {
//        this.groupId = groupId;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee.member_id
     *
     * @return the value of fee.member_id
     *
     * @mbggenerated
     */
//    public Integer getMemberId() {
//        return memberId;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee.member_id
     *
     * @param memberId the value for fee.member_id
     *
     * @mbggenerated
     */
//    public void setMemberId(Integer memberId) {
//        this.memberId = memberId;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee.price
     *
     * @return the value of fee.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee.price
     *
     * @param price the value for fee.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee.management_status_id
     *
     * @return the value of fee.management_status_id
     *
     * @mbggenerated
     */
    public Integer getManagementStatusId() {
        return managementStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee.management_status_id
     *
     * @param managementStatusId the value for fee.management_status_id
     *
     * @mbggenerated
     */
    public void setManagementStatusId(Integer managementStatusId) {
        this.managementStatusId = managementStatusId;
    }


    public String getFeeTypeName() {
        return feeTypeName;
    }

    public void setFeeTypeName(String feeTypeName) {
        this.feeTypeName = feeTypeName;
    }
}