package com.sms.model;

import java.util.Date;

public class Information {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.information_type_id
     *
     * @mbggenerated
     */
    private Integer informationTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.information_subtype_id
     *
     * @mbggenerated
     */
    private Integer informationSubtypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.content_file_path
     *
     * @mbggenerated
     */
    private String contentFilePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.photo_url
     *
     * @mbggenerated
     */
    private String photoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.school_id
     *
     * @mbggenerated
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.branch_school_id
     *
     * @mbggenerated
     */
    private Integer branchSchoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.management_status_id
     *
     * @mbggenerated
     */
    private Integer managementStatusId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.id
     *
     * @return the value of information.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.id
     *
     * @param id the value for information.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.title
     *
     * @return the value of information.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.title
     *
     * @param title the value for information.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.information_type_id
     *
     * @return the value of information.information_type_id
     *
     * @mbggenerated
     */
    public Integer getInformationTypeId() {
        return informationTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.information_type_id
     *
     * @param informationTypeId the value for information.information_type_id
     *
     * @mbggenerated
     */
    public void setInformationTypeId(Integer informationTypeId) {
        this.informationTypeId = informationTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.information_subtype_id
     *
     * @return the value of information.information_subtype_id
     *
     * @mbggenerated
     */
    public Integer getInformationSubtypeId() {
        return informationSubtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.information_subtype_id
     *
     * @param informationSubtypeId the value for information.information_subtype_id
     *
     * @mbggenerated
     */
    public void setInformationSubtypeId(Integer informationSubtypeId) {
        this.informationSubtypeId = informationSubtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.user_id
     *
     * @return the value of information.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.user_id
     *
     * @param userId the value for information.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.created_time
     *
     * @return the value of information.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.created_time
     *
     * @param createdTime the value for information.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.content_file_path
     *
     * @return the value of information.content_file_path
     *
     * @mbggenerated
     */
    public String getContentFilePath() {
        return contentFilePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.content_file_path
     *
     * @param contentFilePath the value for information.content_file_path
     *
     * @mbggenerated
     */
    public void setContentFilePath(String contentFilePath) {
        this.contentFilePath = contentFilePath == null ? null : contentFilePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.photo_url
     *
     * @return the value of information.photo_url
     *
     * @mbggenerated
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.photo_url
     *
     * @param photoUrl the value for information.photo_url
     *
     * @mbggenerated
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl == null ? null : photoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.school_id
     *
     * @return the value of information.school_id
     *
     * @mbggenerated
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.school_id
     *
     * @param schoolId the value for information.school_id
     *
     * @mbggenerated
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.branch_school_id
     *
     * @return the value of information.branch_school_id
     *
     * @mbggenerated
     */
    public Integer getBranchSchoolId() {
        return branchSchoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.branch_school_id
     *
     * @param branchSchoolId the value for information.branch_school_id
     *
     * @mbggenerated
     */
    public void setBranchSchoolId(Integer branchSchoolId) {
        this.branchSchoolId = branchSchoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.management_status_id
     *
     * @return the value of information.management_status_id
     *
     * @mbggenerated
     */
    public Integer getManagementStatusId() {
        return managementStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.management_status_id
     *
     * @param managementStatusId the value for information.management_status_id
     *
     * @mbggenerated
     */
    public void setManagementStatusId(Integer managementStatusId) {
        this.managementStatusId = managementStatusId;
    }
}