package com.sms.model;

import java.util.Date;

public class Member {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.log_name
     *
     * @mbggenerated
     */
    private String logName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.log_password
     *
     * @mbggenerated
     */
    private String logPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.telephone_number
     *
     * @mbggenerated
     */
    private String telephoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.gender
     *
     * @mbggenerated
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.ethnicity
     *
     * @mbggenerated
     */
    private String ethnicity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.photo_url
     *
     * @mbggenerated
     */
    private String photoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.home_address
     *
     * @mbggenerated
     */
    private String homeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.father_name
     *
     * @mbggenerated
     */
    private String fatherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.father_telephone_number
     *
     * @mbggenerated
     */
    private String fatherTelephoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.mother_name
     *
     * @mbggenerated
     */
    private String motherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.mother_telephone_number
     *
     * @mbggenerated
     */
    private String motherTelephoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.group_id
     *
     * @mbggenerated
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.management_status_id
     *
     * @mbggenerated
     */
    private Integer managementStatusId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.id
     *
     * @return the value of member.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.id
     *
     * @param id the value for member.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.log_name
     *
     * @return the value of member.log_name
     *
     * @mbggenerated
     */
    public String getLogName() {
        return logName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.log_name
     *
     * @param logName the value for member.log_name
     *
     * @mbggenerated
     */
    public void setLogName(String logName) {
        this.logName = logName == null ? null : logName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.log_password
     *
     * @return the value of member.log_password
     *
     * @mbggenerated
     */
    public String getLogPassword() {
        return logPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.log_password
     *
     * @param logPassword the value for member.log_password
     *
     * @mbggenerated
     */
    public void setLogPassword(String logPassword) {
        this.logPassword = logPassword == null ? null : logPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.telephone_number
     *
     * @return the value of member.telephone_number
     *
     * @mbggenerated
     */
    public String getTelephoneNumber() {
        return telephoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.telephone_number
     *
     * @param telephoneNumber the value for member.telephone_number
     *
     * @mbggenerated
     */
    public void setTelephoneNumber(String telephoneNumber) {
        this.telephoneNumber = telephoneNumber == null ? null : telephoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.name
     *
     * @return the value of member.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.name
     *
     * @param name the value for member.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.nick_name
     *
     * @return the value of member.nick_name
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.nick_name
     *
     * @param nickName the value for member.nick_name
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.gender
     *
     * @return the value of member.gender
     *
     * @mbggenerated
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.gender
     *
     * @param gender the value for member.gender
     *
     * @mbggenerated
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.birthday
     *
     * @return the value of member.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.birthday
     *
     * @param birthday the value for member.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.ethnicity
     *
     * @return the value of member.ethnicity
     *
     * @mbggenerated
     */
    public String getEthnicity() {
        return ethnicity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.ethnicity
     *
     * @param ethnicity the value for member.ethnicity
     *
     * @mbggenerated
     */
    public void setEthnicity(String ethnicity) {
        this.ethnicity = ethnicity == null ? null : ethnicity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.photo_url
     *
     * @return the value of member.photo_url
     *
     * @mbggenerated
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.photo_url
     *
     * @param photoUrl the value for member.photo_url
     *
     * @mbggenerated
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl == null ? null : photoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.home_address
     *
     * @return the value of member.home_address
     *
     * @mbggenerated
     */
    public String getHomeAddress() {
        return homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.home_address
     *
     * @param homeAddress the value for member.home_address
     *
     * @mbggenerated
     */
    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress == null ? null : homeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.father_name
     *
     * @return the value of member.father_name
     *
     * @mbggenerated
     */
    public String getFatherName() {
        return fatherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.father_name
     *
     * @param fatherName the value for member.father_name
     *
     * @mbggenerated
     */
    public void setFatherName(String fatherName) {
        this.fatherName = fatherName == null ? null : fatherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.father_telephone_number
     *
     * @return the value of member.father_telephone_number
     *
     * @mbggenerated
     */
    public String getFatherTelephoneNumber() {
        return fatherTelephoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.father_telephone_number
     *
     * @param fatherTelephoneNumber the value for member.father_telephone_number
     *
     * @mbggenerated
     */
    public void setFatherTelephoneNumber(String fatherTelephoneNumber) {
        this.fatherTelephoneNumber = fatherTelephoneNumber == null ? null : fatherTelephoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.mother_name
     *
     * @return the value of member.mother_name
     *
     * @mbggenerated
     */
    public String getMotherName() {
        return motherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.mother_name
     *
     * @param motherName the value for member.mother_name
     *
     * @mbggenerated
     */
    public void setMotherName(String motherName) {
        this.motherName = motherName == null ? null : motherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.mother_telephone_number
     *
     * @return the value of member.mother_telephone_number
     *
     * @mbggenerated
     */
    public String getMotherTelephoneNumber() {
        return motherTelephoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.mother_telephone_number
     *
     * @param motherTelephoneNumber the value for member.mother_telephone_number
     *
     * @mbggenerated
     */
    public void setMotherTelephoneNumber(String motherTelephoneNumber) {
        this.motherTelephoneNumber = motherTelephoneNumber == null ? null : motherTelephoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.group_id
     *
     * @return the value of member.group_id
     *
     * @mbggenerated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.group_id
     *
     * @param groupId the value for member.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.created_time
     *
     * @return the value of member.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.created_time
     *
     * @param createdTime the value for member.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.management_status_id
     *
     * @return the value of member.management_status_id
     *
     * @mbggenerated
     */
    public Integer getManagementStatusId() {
        return managementStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.management_status_id
     *
     * @param managementStatusId the value for member.management_status_id
     *
     * @mbggenerated
     */
    public void setManagementStatusId(Integer managementStatusId) {
        this.managementStatusId = managementStatusId;
    }
}