package com.sms.model;

import java.util.Date;

public class Monitor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.group_id
     *
     * @mbggenerated
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.camera_address
     *
     * @mbggenerated
     */
    private String cameraAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.photo_url
     *
     * @mbggenerated
     */
    private String photoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.install_date
     *
     * @mbggenerated
     */
    private Date installDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.id
     *
     * @return the value of monitor.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.id
     *
     * @param id the value for monitor.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.name
     *
     * @return the value of monitor.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.name
     *
     * @param name the value for monitor.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.group_id
     *
     * @return the value of monitor.group_id
     *
     * @mbggenerated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.group_id
     *
     * @param groupId the value for monitor.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.camera_address
     *
     * @return the value of monitor.camera_address
     *
     * @mbggenerated
     */
    public String getCameraAddress() {
        return cameraAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.camera_address
     *
     * @param cameraAddress the value for monitor.camera_address
     *
     * @mbggenerated
     */
    public void setCameraAddress(String cameraAddress) {
        this.cameraAddress = cameraAddress == null ? null : cameraAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.photo_url
     *
     * @return the value of monitor.photo_url
     *
     * @mbggenerated
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.photo_url
     *
     * @param photoUrl the value for monitor.photo_url
     *
     * @mbggenerated
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl == null ? null : photoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.install_date
     *
     * @return the value of monitor.install_date
     *
     * @mbggenerated
     */
    public Date getInstallDate() {
        return installDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.install_date
     *
     * @param installDate the value for monitor.install_date
     *
     * @mbggenerated
     */
    public void setInstallDate(Date installDate) {
        this.installDate = installDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.description
     *
     * @return the value of monitor.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.description
     *
     * @param description the value for monitor.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}