package com.sms.model;

import java.io.Serializable;

public class School implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.telephone_number
     *
     * @mbggenerated
     */
    private String telephoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.school_type_id
     *
     * @mbggenerated
     */
    private Integer schoolTypeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.id
     *
     * @return the value of school.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.id
     *
     * @param id the value for school.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.name
     *
     * @return the value of school.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.name
     *
     * @param name the value for school.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.telephone_number
     *
     * @return the value of school.telephone_number
     *
     * @mbggenerated
     */
    public String getTelephoneNumber() {
        return telephoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.telephone_number
     *
     * @param telephoneNumber the value for school.telephone_number
     *
     * @mbggenerated
     */
    public void setTelephoneNumber(String telephoneNumber) {
        this.telephoneNumber = telephoneNumber == null ? null : telephoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.school_type_id
     *
     * @return the value of school.school_type_id
     *
     * @mbggenerated
     */
    public Integer getSchoolTypeId() {
        return schoolTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.school_type_id
     *
     * @param schoolTypeId the value for school.school_type_id
     *
     * @mbggenerated
     */
    public void setSchoolTypeId(Integer schoolTypeId) {
        this.schoolTypeId = schoolTypeId;
    }
}