package com.sms.model;

import java.util.Date;

public class SchoolInformation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_information.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_information.school_id
     *
     * @mbggenerated
     */
    private Integer schoolId;

    public String getSchoolName() {
        return schoolName;
    }

    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }

    private String schoolName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_information.information_type_id
     *
     * @mbggenerated
     */
    private Integer informationTypeId;

    public String getInformationTypeName() {
        return informationTypeName;
    }

    public void setInformationTypeName(String informationTypeName) {
        this.informationTypeName = informationTypeName;
    }

    public String getInformationSubtypeName() {
        return informationSubtypeName;
    }

    public void setInformationSubtypeName(String informationSubtypeName) {
        this.informationSubtypeName = informationSubtypeName;
    }

    private String informationTypeName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_information.information_subtype_id
     *
     * @mbggenerated
     */
    private Integer informationSubtypeId;

    private String informationSubtypeName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_information.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_information.introduction
     *
     * @mbggenerated
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_information.photo_url
     *
     * @mbggenerated
     */
    private String photoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_information.content_file_path
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_information.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_information.management_status_id
     *
     * @mbggenerated
     */
    private Integer managementStatusId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_information.id
     *
     * @return the value of school_information.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_information.id
     *
     * @param id the value for school_information.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_information.school_id
     *
     * @return the value of school_information.school_id
     *
     * @mbggenerated
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_information.school_id
     *
     * @param schoolId the value for school_information.school_id
     *
     * @mbggenerated
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_information.information_type_id
     *
     * @return the value of school_information.information_type_id
     *
     * @mbggenerated
     */
    public Integer getInformationTypeId() {
        return informationTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_information.information_type_id
     *
     * @param informationTypeId the value for school_information.information_type_id
     *
     * @mbggenerated
     */
    public void setInformationTypeId(Integer informationTypeId) {
        this.informationTypeId = informationTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_information.information_subtype_id
     *
     * @return the value of school_information.information_subtype_id
     *
     * @mbggenerated
     */
    public Integer getInformationSubtypeId() {
        return informationSubtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_information.information_subtype_id
     *
     * @param informationSubtypeId the value for school_information.information_subtype_id
     *
     * @mbggenerated
     */
    public void setInformationSubtypeId(Integer informationSubtypeId) {
        this.informationSubtypeId = informationSubtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_information.title
     *
     * @return the value of school_information.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_information.title
     *
     * @param title the value for school_information.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_information.introduction
     *
     * @return the value of school_information.introduction
     *
     * @mbggenerated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_information.introduction
     *
     * @param introduction the value for school_information.introduction
     *
     * @mbggenerated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_information.photo_url
     *
     * @return the value of school_information.photo_url
     *
     * @mbggenerated
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_information.photo_url
     *
     * @param photoUrl the value for school_information.photo_url
     *
     * @mbggenerated
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl == null ? null : photoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_information.content_file_path
     *
     * @return the value of school_information.content_file_path
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_information.content_file_path
     *
     * @param content the value for school_information.content_file_path
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_information.created_time
     *
     * @return the value of school_information.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_information.created_time
     *
     * @param createdTime the value for school_information.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_information.management_status_id
     *
     * @return the value of school_information.management_status_id
     *
     * @mbggenerated
     */
    public Integer getManagementStatusId() {
        return managementStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_information.management_status_id
     *
     * @param managementStatusId the value for school_information.management_status_id
     *
     * @mbggenerated
     */
    public void setManagementStatusId(Integer managementStatusId) {
        this.managementStatusId = managementStatusId;
    }
}