package com.sms.model;

import java.util.Date;

public class StudentReport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_report.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_report.member_id
     *
     * @mbggenerated
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_report.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_report.report_type_id
     *
     * @mbggenerated
     */
    private Integer reportTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_report.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_report.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_report.content_file_path
     *
     * @mbggenerated
     */
    private String contentFilePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_report.photo_url
     *
     * @mbggenerated
     */
    private String photoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_report.management_status_id
     *
     * @mbggenerated
     */
    private Integer managementStatusId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_report.id
     *
     * @return the value of student_report.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_report.id
     *
     * @param id the value for student_report.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_report.member_id
     *
     * @return the value of student_report.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_report.member_id
     *
     * @param memberId the value for student_report.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_report.title
     *
     * @return the value of student_report.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_report.title
     *
     * @param title the value for student_report.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_report.report_type_id
     *
     * @return the value of student_report.report_type_id
     *
     * @mbggenerated
     */
    public Integer getReportTypeId() {
        return reportTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_report.report_type_id
     *
     * @param reportTypeId the value for student_report.report_type_id
     *
     * @mbggenerated
     */
    public void setReportTypeId(Integer reportTypeId) {
        this.reportTypeId = reportTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_report.user_id
     *
     * @return the value of student_report.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_report.user_id
     *
     * @param userId the value for student_report.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_report.created_time
     *
     * @return the value of student_report.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_report.created_time
     *
     * @param createdTime the value for student_report.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_report.content_file_path
     *
     * @return the value of student_report.content_file_path
     *
     * @mbggenerated
     */
    public String getContentFilePath() {
        return contentFilePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_report.content_file_path
     *
     * @param contentFilePath the value for student_report.content_file_path
     *
     * @mbggenerated
     */
    public void setContentFilePath(String contentFilePath) {
        this.contentFilePath = contentFilePath == null ? null : contentFilePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_report.photo_url
     *
     * @return the value of student_report.photo_url
     *
     * @mbggenerated
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_report.photo_url
     *
     * @param photoUrl the value for student_report.photo_url
     *
     * @mbggenerated
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl == null ? null : photoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_report.management_status_id
     *
     * @return the value of student_report.management_status_id
     *
     * @mbggenerated
     */
    public Integer getManagementStatusId() {
        return managementStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_report.management_status_id
     *
     * @param managementStatusId the value for student_report.management_status_id
     *
     * @mbggenerated
     */
    public void setManagementStatusId(Integer managementStatusId) {
        this.managementStatusId = managementStatusId;
    }
}