package com.sms.model;

public class UserSchoolGroupAssociation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_school_group_association.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_school_group_association.school_id
     *
     * @mbggenerated
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_school_group_association.branch_school_id
     *
     * @mbggenerated
     */
    private Integer branchSchoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_school_group_association.group_id
     *
     * @mbggenerated
     */
    private Integer groupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_school_group_association.user_id
     *
     * @return the value of user_school_group_association.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_school_group_association.user_id
     *
     * @param userId the value for user_school_group_association.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_school_group_association.school_id
     *
     * @return the value of user_school_group_association.school_id
     *
     * @mbggenerated
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_school_group_association.school_id
     *
     * @param schoolId the value for user_school_group_association.school_id
     *
     * @mbggenerated
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_school_group_association.branch_school_id
     *
     * @return the value of user_school_group_association.branch_school_id
     *
     * @mbggenerated
     */
    public Integer getBranchSchoolId() {
        return branchSchoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_school_group_association.branch_school_id
     *
     * @param branchSchoolId the value for user_school_group_association.branch_school_id
     *
     * @mbggenerated
     */
    public void setBranchSchoolId(Integer branchSchoolId) {
        this.branchSchoolId = branchSchoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_school_group_association.group_id
     *
     * @return the value of user_school_group_association.group_id
     *
     * @mbggenerated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_school_group_association.group_id
     *
     * @param groupId the value for user_school_group_association.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
}